### PR TITLE
[WIP] JBIDE-27036 - Refactor pom.xml for project-examples itests

### PR DESCRIPTION
**Pull request by zcervink**
JBIDE-27036 - Refactor pom.xml for project-examples itests

**JIRA:** https://issues.redhat.com/browse/JBIDE-27036
**JENKINS:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.eap.it.weekly/831/

Please review @odockal @jkopriva - I have removed the smoke suite profiles. Target platform configuration repeats on more places, but the requirements in the <configuration> differ on each place, I suggest to keep it this way, otherwise I do not know how to perform the refactoring (using pluginManagement? Merge all the requirements to one <configuration>?).

### CODE REVIEW

**Comment by jkopriva** [comment]
@zcervink what about check-pr profile? Is it used anywhere? AFAIK this is not used anymore.
I can see other duplicates like 
https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/org.jboss.tools.examples.ui.bot.test/pom.xml#L601
https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/org.jboss.tools.examples.ui.bot.test/pom.xml#L655

Maybe also build parts could be reworked too....

**Comment by zcervink** [comment]
testPR

**Comment by zcervink** [comment]
@jkopriva I have removed the duplicates you have mentioned and I have found some more. I think, now it can be finally merged.

New Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/DSL%20Jobs%20seed/job/Studio/job/Quality/job/Integration-tests/job/examples-javaee-8-itests/42/

**Comment by zcervink** [comment]
@jkopriva what do you think about this PR?

**Comment by jkopriva** [comment]
@zcervink I am looking at all profiles and there are two steps: 1. download quickstarts, 2. download server. What if we put this parts in build and just change parameters?
Something like: 
image

**Comment by zcervink** [comment]
@jkopriva I have looked at the code and the redundancy is something we should take seriously. On the other hand if we move the code to build we have to parametrize that code and add links to server/examples to JOB DSL defined Jenkins jobs and update them every time we update to newer version of server. Do you really want me to do that?

**Comment by jkopriva** [comment]
@zcervink why do you need to put parameters in jobdsl? I suppose it will be enough to just delete steps for downloading server/quickstarts in every profile and put these steps in build step - as it is shown in screenshot.

**Pull request closed without merging**
