### PR TITLE
JBIDE-23725 - Adding missing CDI itests

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jkopriva Please, take a look. Header will be added.

**Comment by odockal** [comment]
Job: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/Devstudio/view/devstudio_integration_tests/job/cdi11.itests/377

**Comment by jkopriva** [comment]
@odockal please add copyright

**Comment by jkopriva** [comment]
LGTM, merging :)

**Pull request merged**
