### PR TITLE
[JBIDE-23499] fixed and merged ConnectionWizardLinkTest

### PR DESCRIPTION
**Pull request by adietish**
* fixed ConnectionWizardLinkTest to login into CDK via OAuth (was trying to use openshift 3 online preview with a disabled account)
* renamed the single test method in it and moved into CreateNewConnectionTest

### CODE REVIEW

**Comment by adietish** [comment]
@mlabuda @rhopp please review

**Comment by mlabuda** [comment]
Please revert changes in Smoke suite, there are commented out test classes. Probably forgotten from testing this PR. Only remove the link test class. Otherwise look good to me.

**Comment by adietish** [comment]
@mlabuda good catch, forghot to revert this. Done now.

**Comment by mlabuda** [comment]
LGTM +1

**Comment by adietish** [comment]
@rhopp can you please merge this?

**Pull request merged**
