### PR TITLE
JBIDE-27296: update docker client

### PR DESCRIPTION
**Pull request by sbouchet**
Signed-off-by: Stephane Bouchet <sbouchet@redhat.com>

# Pull Request Checklist

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?
* Is copyright with correct year in new files?
* Is there a JavaDoc in every class with description of a class and an author(and JIRA if suitable)?
* Is there a link to JIRA? (if needed)

## Testing
* Does it work?
* Are the tests green on Jenkins? Is there a link to Jenkins build?

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@sbouchet Multiple compilation errors.. Imports require update (package com.spotify -> org.mandas or similar)...

**Comment by sbouchet** [comment]
testPR

**Comment by sbouchet** [comment]
testPR

**Pull request merged**
