### PR TITLE
[JBIDE-23497] made test suite-indep, possibly wait for ssl cert dialog

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@mlabuda @rhopp please review

**Comment by mlabuda** [comment]
- add securestorage.password property to pom.xml to system properties.
- update README.md (include securestorage.password property)

**Comment by adietish** [comment]
@mlabuda ok for the updates, I'll include those of course.
Your other report is rather odd because there's the explicit check for auth method in the static initializiation:
```
		assertNotNull("Please add '-D" + KEY_AUTHMETHOD + "=[basic|oauth]' to your launch arguments", authMethod);
```
What makes you think that the above error, where a class is not being found is caused by AuthenticationMethod.safeValueOf?

**Comment by adietish** [comment]
The problem wasnt AuthenticationMethod#safeValueOf but missing system properties in org.jboss.tools.openshift.ui.bot.test/pom.xml, especially the -Dsecurestorage.password=1q5t9o3e
I fixed it and now tests wont show the NoClassDefFound any more.
Nevertheless, I agree that the static design of DataStoreOS3/OS2 isnt state of the art.

**Comment by mlabuda** [comment]
To replicate the NoClassDefFound, run OpenShift 3 test from suite and use only this arguments:
-Dopenshift.server=https://10.1.2.2:8443 -Dopenshift.username=openshift-dev -Dopenshift.password=devel -Dsecurestorage.password=whatever -Dusage_reporting_enabled=false

Don't use openshift.authmethod there occasionally. You will see tests in errors starting from test class CreateNewConnectionTest with following stack:
`java.lang.NoClassDefFoundError: Could not initialize class org.jboss.tools.openshift.reddeer.utils.DatastoreOS3
	at org.jboss.tools.openshift.reddeer.view.OpenShiftExplorerView.getOpenShift3Connection(OpenShiftExplorerView.java:253)
	at org.jboss.tools.openshift.ui.bot.test.project.CreateNewProjectTest.testCreateNewProjectViaContextMenu(CreateNewProjectTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.jboss.reddeer.junit.internal.runner.statement.RunTestMethod.evaluate(RunTestMethod.java:46)
	at org.jboss.reddeer.junit.internal.runner.statement.RunBefores.evaluate(RunBefores.java:79)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIBeforeTestExtensions.evaluate(RunIBeforeTestExtensions.java:73)
	at org.jboss.reddeer.junit.internal.runner.statement.RunAfters.evaluate(RunAfters.java:68)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIAfterTestExtensions.evaluate(RunIAfterTestExtensions.java:61)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.jboss.reddeer.junit.internal.runner.RequirementsRunner.runChild(RequirementsRunner.java:171)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.jboss.reddeer.junit.internal.runner.statement.RunBefores.evaluate(RunBefores.java:79)
	at org.jboss.reddeer.junit.internal.runner.statement.FulfillRequirementsStatement.evaluate(FulfillRequirementsStatement.java:45)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIBeforeClassExtensions.evaluate(RunIBeforeClassExtensions.java:72)
	at org.jboss.reddeer.junit.internal.runner.statement.RunAfters.evaluate(RunAfters.java:68)
	at org.jboss.reddeer.junit.internal.runner.statement.CleanUpRequirementStatement.evaluate(CleanUpRequirementStatement.java:44)
	at org.jboss.reddeer.junit.internal.runner.statement.RunIAfterClassExtensions.evaluate(RunIAfterClassExtensions.java:59)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.jboss.reddeer.junit.internal.runner.RequirementsRunner.run(RequirementsRunner.java:153)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.jboss.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:68)
	at org.jboss.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable$1.run(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:745)

`

**Comment by adietish** [comment]
@mlabuda when running the following
```
mvn clean verify -Dopenshift.server=https://10.1.2.2:8443 -Dopenshift.username=openshift-dev -Dopenshift.password=devel -Dsecurestorage.password=whatever -Dusage_reporting_enabled=false -Dtest=CreateNewConnectionTest -DskipTests=false
```
i have the following output which differs from yours
```
10:54:45.404 ERROR [WorkbenchTestable][RunTestMethod] Test org.jboss.tools.openshift.ui.bot.test.connection.v3.CreateNewConnectionTest.shouldExtractTokenInBrowserWindow throws exception: 
java.lang.AssertionError: Please add '-Dopenshift.authmethod=[basic|oauth]' to your launch arguments
```
What do I miss?

**Comment by mlabuda** [comment]
You are running a single test class, not a test suite (you should run a test suite). And you are doing it from CLI. From CLI it is also reproducible, but has cut off error message, but NoClassDefFound is visible too.

**Comment by mlabuda** [comment]
Also notice, you have to run it from IDE, if you run it from CLI, it somehow show correct output (as you have). But from IDE I am getting NoClassDefFound when initializing DatastoreOS3.

**Comment by adietish** [comment]
@mlabuda running from IDE and/or running all the suite results in the above error for me. What do I miss?

**Comment by mlabuda** [comment]
In your amended commit you changed it a bit so maybe it got fixed. I have not checked your latest changes yet.

**Comment by adietish** [comment]
@mlabuda ok, so yes please, check this latest commit. To me your complaint is fixed with the latest commit.

**Comment by adietish** [comment]
@mlabuda could you please verify the latest update?

**Comment by adietish** [comment]
@mlabuda I rebased and ran the above command (missing argument -Dopenshift.authmethod):
```
mvn clean verify -Dopenshift.server=https://10.1.2.2:8443 -Dopenshift.username=openshift-dev -Dopenshift.password=devel -Dsecurestorage.password=whatever -Dusage_reporting_enabled=false -Dtest=CreateNewConnectionTest -DskipTests=false
```
The output was the expected error message telling you that you need to provide the -Dopenshift.authmethod parameter:
```
12:57:50.534 ERROR [WorkbenchTestable][RunTestMethod] Test org.jboss.tools.openshift.ui.bot.test.connection.v3.CreateNewConnectionTest.shouldExtractTokenInBrowserWindow throws exception: 
java.lang.AssertionError: Please add '-Dopenshift.authmethod=[basic|oauth]' to your launch arguments
```
please review.

**Comment by mlabuda** [comment]
LGTM. @rhopp you can proceed with review/merge.

**Pull request merged**
