### PR TITLE
Update WildFly to version 22 in examples.itests

### PR DESCRIPTION
**Pull request by zcervink**
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

**Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/109/
**Jira:** https://issues.redhat.com/browse/JBIDE-27566

Please review @jkopriva

### CODE REVIEW

**Review by jkopriva — CHANGES_REQUESTED** [review]
What about this line? 
https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/org.jboss.tools.examples.ui.bot.test/pom.xml#L18

**Comment by zcervink** [comment]
@jkopriva Fixed, **Jenkins:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/111/

**Comment by jkopriva** [comment]
testPR

**Comment by jkopriva** [comment]
@zcervink can you please also review and update blacklist and test-errors-regexes? Thanks!

**Comment by zcervink** [comment]
@jkopriva I have reviewed them, there are no updates needed.

**Comment by zcervink** [comment]
testPR

**Comment by zcervink** [comment]
@jkopriva I have updated the blacklist, Jenkins here: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/136/

**Comment by zcervink** [comment]
@jkopriva Rebase was inevitable (check were failing), so I have rerun the Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/138/

**Comment by jkopriva** [comment]
@zcervink I have several comments: 
- I have tried to import jsonp Quickstart in new workspace and the import was without issues
- ebb-multi-server quickstart is blacklisted, but can be imported - only some warnings are shown
- what about Checkstyle issues? You have issue for this: https://issues.redhat.com/browse/JBIDE-26830, but it has not been updated for some time and also when I manually import quickstart and install required plugin no error is shown.

Checkstyle fix could be in different PR, but issues related to quickstart should be reviewed in this PR.

**Comment by zcervink** [comment]
@jkopriva Yes you are right, the checkstyle issue is now gone. I have already removed also the ebb-multi-server item from the blacklist. The jsonp should be kept in blacklist - it has issues on rhel8 and win10 also the kitchensink-ml needs to be blacklisted, it has issues on ubuntu2010

- https://issues.redhat.com/browse/JBIDE-27718
- https://issues.redhat.com/browse/JBIDE-27720

**It can be seen on this Jenkins run:**
https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/130/

**And here is updated Jenkins run for the last commit:**
https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/139/

**Comment by zcervink** [comment]
@jkopriva I have removed the 2 quickstarts from the blacklist. I have also add again the Checkstyle to the blacklist, the issue has appeared again (probably the issue was there always, it just sometimes shows, sometimes not).

**Jenkins with the checkstyle issue:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/145/jdk=openjdk-11,label=rhel8/testReport/

**Jenkins for this PR:** https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-wildfly-itests/146/

**Review by jkopriva — APPROVED** [review]

**Pull request merged**
