### PR TITLE
Add execution priority for SetMavenUserSettings

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by nickboldt** [comment]
retest this please

**Comment by odockal** [comment]
retest this please

**Comment by nickboldt** [comment]
retest this please

**Comment by nickboldt** [comment]
retest this please

**Comment by odockal** [comment]
retest this please

**Comment by rawagner** [comment]
requires RedDeer 1.1.0.Final on TP

**Comment by rhopp** [comment]
test this

**Pull request merged**
