### PR TITLE
JBIDE-24003 Tests extended to use CDKv3 server adapter changes

### PR DESCRIPTION
**Pull request by odockal**

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
Requires [PR](https://github.com/jbosstools/jbosstools-openshift/pull/1466) to be merged first.

**Comment by jkopriva** [comment]
testPR

**Comment by rhopp** [comment]
testPR

**Comment by rhopp** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Pull request merged**
