### PR TITLE
[JBIDE-23491] dont have cleanup failing if no connection/projs

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by adietish** [comment]
@mlabuda @rhopp can you please review and merge this?

**Comment by rhopp** [comment]
testPR

**Comment by rhopp** [comment]
Build passed (those two failing checks don't belong here, @ldimaggi will hopefully fix it soon ;-)), @mlabuda reviewed this PR. Merging

**Comment by adietish** [comment]
thx!

**Pull request merged**
