### PR TITLE
JBIDE-26645 - Fix the itests in job examples.eap.it.weekly

### PR DESCRIPTION
**Pull request by zcervink**
- update EAP server to 7.2.1 and fix issues

Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.eap.it.weekly/650/
Jira: https://issues.jboss.org/browse/JBIDE-26645
@jkopriva please review

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

### CODE REVIEW

**Comment by jkopriva** [comment]
@zcervink Have you verified also eap-blacklist-test-errors-regexes.json file if all of its contents is still relevant?

**Comment by zcervink** [comment]
> @zcervink Have you verified also eap-blacklist-test-errors-regexes.json file if all of its contents is still relevant?

@jkopriva I have verified the "eap-blacklist-test-errors-regexes.json" and the "eap-blacklist" files, several entries were removed. All he remaining entries are verified and needed.

**Comment by zcervink** [comment]
testPR

**Comment by zcervink** [comment]
@jkopriva After consultation with Pavel Jelínek I have reported the "spring-greeter" issue including tested solution:

https://issues.jboss.org/browse/WFLY-12183
https://issues.jboss.org/browse/JBEAP-17039

**Pull request merged**
