### PR TITLE
JBIDE-26845 - Update WildFly to version 18 in examples.wildfly.itests

### PR DESCRIPTION
**Pull request by zcervink**
JBIDE-26845 - Update WildFly to version 18 in examples.wildfly.itests and check and update entries in the wildfly-blacklist and wildfly-blacklist-test-errors-regexes.json files

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

Please review @odockal @jkopriva 

**Jira:** https://issues.jboss.org/browse/JBIDE-26845
**Jenkins:** soon in a comment below

### CODE REVIEW

**Comment by jkopriva** [comment]
Just note for improvement: what about changing wildfly-18.json to wildfly.json and creating variable in pom like <wildflyVersion>18.0.0.Final</wildflyVersion>, so you do not have to change it every time on so many places.

**Comment by zcervink** [comment]
@jkopriva
- **wildfly-17.jso**n has been renamed to **wildfly.json**
- the **<wildflyVersion>18.0.0.Final</wildflyVersion>** variable has been created and used to parametrise the pom.xml


**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.wildfly.it.weekly/620/

**Comment by zcervink** [comment]
Updated Jenkins: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.wildfly.it.weekly/633/

**Comment by zcervink** [comment]
@jkopriva @odockal I have update on this PR, after some customizations in the blacklist file I have finally Jenkins OK (except the _**Exception during sync execution in UI thread**_ issue)

**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/examples.wildfly.it.weekly/656/

**Comment by jkopriva** [comment]
@zcervink please rebase and restart build. Thanks!

**Comment by jkopriva** [comment]
LGTM

**Pull request merged**
