### PR TITLE
JBIDE-21725 Remove RedDeer repo properties from integration tests

### PR DESCRIPTION
**Pull request by mmalina**
The reddeer-site property is now set in parent pom so that other
repos may consume it if needed.

### CODE REVIEW

**Comment by nickboldt** [comment]
Are you sure that {reddeer-stable-site} isn't used anywhere?

Also, you have a variable for eclipseName = neon. You could just use the eclipseReleaseName in parent pom.

https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L17

**Comment by mmalina** [comment]
@nickboldt , I did do a lookup for reddeer-site in all poms and did't find it anywhere.

You have a valid point with eclipseName, but that's not relevant to this PR really ;)

But I'll add another commit with that and we can merge it together.

**Comment by mmalina** [comment]
New commit added.

**Comment by nickboldt** [comment]
+1

**Comment by rhopp** [comment]
Pushed to master(ef8f7e65fe8c8c3ca940e764467df8b26aa67d41, 3fbc052affe82a971a55ea9981c4c0e5233a9a09). Closing.

**Pull request closed without merging**
