### PR TITLE
Added tests for maven scm wizard import

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by psrna** [comment]
Please fix the build errors from verification job. Thanks

**Comment by rawagner** [comment]
I will have to wait for this reddeer PR https://github.com/jboss-reddeer/reddeer/pull/1229

**Comment by psrna** [comment]
Retest this please.

**Comment by psrna** [comment]
Retest this please.

**Comment by psrna** [comment]
Pushed to master.

**Pull request closed without merging**
