### PR TITLE
Smoke test plug-in removed in favor of individual component smoke suites

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by maxandersen** [comment]
hmm - so why are we removing a testsuite we can actually use to run smoketests in one go ?

**Comment by vpakan** [comment]
Because we decided to define smoke tests set per per component i.e. each test plugins define SmokeSuite containing smoke tests for particular component and automated build runs all SmokeSuites across all JBT integration test plugins

**Comment by maxandersen** [comment]
okey - so is there a way to run all tests in one go ?

**Comment by mmalina** [comment]
@maxandersen you should be able to just run "mvn verify -P smoke" in the root of the repo.

**Pull request merged**
