### PR TITLE
[JBIDE-23648] fixed ImageTagTest#addUpperCaseTagToImage

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@jkopriva please review

**Comment by rhopp** [comment]
I don't think is a good move. I would leave this test failing until it is fixed in tooling (or upstream?). Artificially marking failing test as passing induces high risk of omitting to undo this change when the issue is fixed.

**Comment by adietish** [comment]
@rhopp @jeffmaury the aim here is to make the suite blue, as we discussed and agreed in the last meeting. 
When using the @Test(expected=) approach the test will actually start to fail once the docker tooling is fixed upstream. So there is no danger this is going to be forgotten. On the contrary, it catches the expected current state of the tooling.

**Comment by jeffmaury** [comment]
@rhopp @adietish I agree with André the goal is to have a test suite blue for automated testing and using expected clause will make the test to fail when the issue will be fixed. Anything that does require an light or heavy analysis of the results will fail because dev will then no use those tests

**Comment by adietish** [comment]
It looks as if we should only expect the error dialog not to show up if the docker daemon being used is < 1.11. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=509223#c2

**Comment by adietish** [comment]
so for now we decided to assert the tagging error (when using uppercase tags) for docker daemons >= 1.11, while we dont for the ones below. The test will get green.
Whenever something is moving in the Eclipse Docker tooling we'll notice and be able to catch up in our test.

**Comment by jkopriva** [comment]
@rhopp @psrna fix is working, please review and merge

**Comment by rhopp** [comment]
Merging without verifcation job (there is some problem in jenkins with provisioning slaves).

**Pull request merged**
