### PR TITLE
Update and refactor ws-rest itests, fixes JBIDE-27021

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

# Pull Request Checklist

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?
* Is copyright with correct year in new files?
* Is there a JavaDoc in every class with description of a class and an author(and JIRA if suitable)?
* Is there a link to JIRA? (if needed)

## Testing
* Does it work?
* Are the tests green on Jenkins? Is there a link to Jenkins build?

### CODE REVIEW

**Comment by odockal** [comment]
Requires https://github.com/jbosstools/jbosstools-webservices/pull/304 to be merged and built first.

**Comment by odockal** [comment]
SOAP tests: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/jax-ws-itests/12/
REST tests - 1 unstable, do not know why yet: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/jax-rs-itests/13/
Socket tests to come.

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jkopriva 
JAX-RS tests: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/jax-rs-itests/16/ - 1 is failing, will be addressed later.
JAX-WS: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/jax-ws-itests/16/ - also 1 failing, will be addressed later.
Web services sockets: https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CodeReady%20Studio%20QE/job/Studio/job/Quality/job/Integration-tests/job/jax-socket-itests/2/

**Comment by odockal** [comment]
@jkopriva date to take a look, please?

**Comment by odockal** [comment]
@jkopriva Thanks!

**Comment by jkopriva** [comment]
np :)

**Pull request merged**
