### PR TITLE
[JBIDE-23502] allow ConnectionPropertiesTest to run individ.

### PR DESCRIPTION
**Pull request by adietish**

### CODE REVIEW

**Comment by adietish** [comment]
@mlabuda @rhopp plz review

**Comment by mlabuda** [comment]
How should this syntactic changes fix the problem with JBT? I see only replaced assertTrue by assertEquals and extracting property names.

**Comment by mlabuda** [comment]
Look good to me. +1

**Comment by adietish** [comment]
@mlabuda thx
@rhopp can you please merge this?

**Pull request merged**
