### PR TITLE
Update EAP XP to 2.0.0.GA-CR1

### PR DESCRIPTION
**Pull request by jkopriva**
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

# Pull Request Checklist

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?
* Is copyright with correct year in new files?
* Is there a JavaDoc in every class with description of a class and an author(and JIRA if suitable)?
* Is there a link to JIRA? (if needed)

## Testing
* Does it work?
* Are the tests green on Jenkins? Is there a link to Jenkins build?

### CODE REVIEW

**Comment by jkopriva** [comment]
https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/examples-eap-xp-itests/lastCompletedBuild/testReport/

**Review by jeffmaury — CHANGES_REQUESTED** [review]
You did not get it: I requested a change to XP 2.0.0 CR1

**Comment by jkopriva** [comment]
@jeffmaury sorry, now it should be correct version :)

**Review by odockal — APPROVED** [review]

**Review by jeffmaury — COMMENTED** [review]
Not sure where this is configured but EAPXP 2 requires patch 4 for EAP 7.3 and I think we also had a similar requirement for EAPXP 1 (but with patch 1)

**Comment by jkopriva** [comment]
@jeffmaury this downloads also EAP server, which is in the same folder with these EAP XP quickstarts. I have just checked it and it is 7.3.4.GA

**Review by jeffmaury — APPROVED** [review]

**Pull request merged**
