### PR TITLE
Batch test project for java 1.8 and 11

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

# Pull Request Checklist

## Code
* Are method-/class-/variable-names meaningful?
* Are methods concise, not too long?
* Are catch blocks catching precise Exceptions only (no catch all)?
* Is copyright with correct year in new files?
* Is there a link to JIRA? (if needed)

## Testing
* Does it work?
* Are the tests green on Jenkins? Is there a link to Jenkins build?

### CODE REVIEW

**Comment by jkopriva** [comment]
@odockal can you please review sonar issues? You can easily move duplicated code to abstract class.

**Comment by odockal** [comment]
@jkopriva not really. All classes extend that one abstract class but not all classes requires such before class use, it differs there for others.

**Comment by jkopriva** [comment]
LGTM

**Comment by odockal** [comment]
thanks!

**Pull request merged**
