### PR TITLE
Extended timeouts to make tests more reliable. Added workaround for i…

### PR DESCRIPTION
**Pull request by ldimaggi**
…ntermittent problem with: Red Deer issue: https://github.com/jboss-reddeer/reddeer/issues/1300

### CODE REVIEW

**Comment by vpakan** [comment]
Should this be applied only to master or also to jbosstools-4.3.x branch?

**Comment by ldimaggi** [comment]
Sorry! Yes - it should be 4.3 also - thanks!

On Thu, Nov 12, 2015 at 10:41 AM, Vlado Pakan <notifications@github.com>
wrote:

> Should this be applied only to master or also to jbosstools-4.3.x branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbosstools/jbosstools-integration-tests/pull/1281#issuecomment-156142833>
> .
>



-- 
Len DiMaggio (ldimaggi@redhat.com)
JBoss by Red Hat
314 Littleton Road
Westford, MA 01886  USA
tel:  978.392.3179
cell: 781.472.9912
http://www.redhat.com
http://community.jboss.org/people/ldimaggio

**Comment by vpakan** [comment]
So create PR for branch

**Comment by ldimaggi** [comment]
OK - done - have a look!

On Thu, Nov 12, 2015 at 12:30 PM, Vlado Pakan <notifications@github.com>
wrote:

> So create PR for branch
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jbosstools/jbosstools-integration-tests/pull/1281#issuecomment-156175769>
> .
>



-- 
Len DiMaggio (ldimaggi@redhat.com)
JBoss by Red Hat
314 Littleton Road
Westford, MA 01886  USA
tel:  978.392.3179
cell: 781.472.9912
http://www.redhat.com
http://community.jboss.org/people/ldimaggio

**Comment by vpakan** [comment]
Waiting for #1282 to be properly created

**Pull request closed without merging**
