### PR TITLE
JBIDE-23093 Adapt to variable changes in parent pom

### PR DESCRIPTION
**Pull request by mmalina**
jbosstools_site_stream is now stream_jbt

### CODE REVIEW

**Comment by mmalina** [comment]
Unfortunately I could not verify it still builds because the build is currently broken for me:
https://issues.jboss.org/browse/JBIDE-23380

**Comment by rhopp** [comment]
Could you, please, rebase on master (there are conflicts in pom.xml). Thanks

**Comment by rhopp** [comment]
Is this PR still needed @mmalina ?

**Comment by mmalina** [comment]
@rhopp yes, why wouldn't it? :)
See here:
https://github.com/jbosstools/jbosstools-build/blob/master/parent/pom.xml#L94
jbosstools_site_stream is deprecated.

**Comment by rhopp** [comment]
Could you resolve conflicts, so I can merge it?

**Comment by mmalina** [comment]
@rhopp ok, I rebased and resolved the conflict. Ready to be merged.

**Comment by rhopp** [comment]
Thanks!

**Pull request merged**
