### PR TITLE
[JBIDE-23597] removed ticketmonster.ui.bot.test since deprecated

### PR DESCRIPTION
**Pull request by adietish**
ticketmonster is not maintained any more. So there's no value in having
automated tests for it any more.

### CODE REVIEW

**Comment by adietish** [comment]
@rawagner please review

**Comment by rawagner** [comment]
can you please also remove it from category.xml ? 

https://github.com/jbosstools/jbosstools-integration-tests/blob/master/site/category.xml#L70
and 
https://github.com/jbosstools/jbosstools-integration-tests/blob/master/site/category.xml#L134

**Comment by adietish** [comment]
@rawagner sure thing, thanks for pointing out.
done.

**Comment by rawagner** [comment]
LGTM

**Comment by adietish** [comment]
@rhopp can you please merge this?

**Comment by rawagner** [comment]
testPR

**Pull request merged**
