### PR TITLE
JBIDE-23656 - Missing validation of step listener with empty attribute ref

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
testPR

**Comment by odockal** [comment]
@jeffmaury Could you please rebase branch of this PR, because of compilation error from broken api? Thanks!

**Comment by jeffmaury** [comment]
@odockal Done

**Comment by rhopp** [comment]
testPR

**Pull request merged**
