### PR TITLE
Update WildFly to version 22 in maven.itests

### PR DESCRIPTION
**Pull request by zcervink**
Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

Jira: https://issues.redhat.com/browse/JBIDE-27567
Jenkins: https://studio-jenkins-csb-codeready.cloud.paas.psi.redhat.com/job/Studio/job/Quality/job/Integration-tests/job/maven-itests/149/

Please review @jkopriva

### CODE REVIEW

**Comment by jkopriva** [comment]
@zcervink do you also have JIRAs/fixes for failing tests? for example maven conversion test is failing for some time....

**Comment by zcervink** [comment]
@jkopriva Yes, I have.

**Comment by jkopriva** [comment]
@zcervink Please also add links

**Comment by zcervink** [comment]
@jkopriva Here is a jira for the failing maven itests - https://issues.redhat.com/browse/JBIDE-27675

**Comment by jkopriva** [comment]
@zcervink please update JIRA with details, merging this PR.

**Pull request merged**
