### PR TITLE
Tests of Deltaspike Security module enhanced.

### PR DESCRIPTION
**Pull request by luvalach**
New tests includes:
-test of @Secured annotation on the Class level
-test of detection of multiple secutity bindings

### CODE REVIEW

**Comment by vpakan** [comment]
Can one of the admins verify this patch?

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
test this

**Pull request merged**
