### PR TITLE
Fixed perform freemarker run UI test

### PR DESCRIPTION
**Pull request by jpeterka**

### CODE REVIEW

**Comment by vpakan** [comment]
Verification job failed

**Comment by jpeterka** [comment]
Failure is caused by https://issues.jboss.org/browse/JBIDE-20920 , not related to this PR

**Comment by vpakan** [comment]
I know but have to wait until verification job works again

**Comment by vpakan** [comment]
Waiting for changes to be pushed to RedDeer and possibly fix this error.

**Comment by vpakan** [comment]
Should it be pushed also to jbosstools-4.3.x branch?

**Pull request merged**
