### PR TITLE
JBIDE-18772: Fix deployment src and dest

### PR DESCRIPTION
**Pull request by mickaelistria**

### CODE REVIEW

**Comment by vpakan** [comment]
Verification job failed:
```
[ERROR] Failed to execute goal org.jboss.tools.tycho-plugins:repository-utils:0.22.1-SNAPSHOT:generate-repository-facade (generate-facade) on project site: Could not get upstream metadata: IllegalArgumentException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :site
```

Please check

**Comment by mickaelistria** [comment]
I don't see how this change would cause the error verification job got. A local "mvn clean verify -DskipTests" did work locally. Can you please try to re-run it?

**Comment by vpakan** [comment]
To rerun verification just add comment containing 'test this'

**Comment by vpakan** [comment]
test this

**Comment by vpakan** [comment]
Failed again

**Comment by vpakan** [comment]
Maven command line from Jenkins job are:

mvn ... -DskipTests=true -Dmaven.test.failure.ignore=true -Dswtbot.test.skip=true -U clean verify

**Comment by vpakan** [comment]
i did run it locally and got the same error

**Comment by vpakan** [comment]
Even with mvn clean verify -DskipTests I have got the same error.

**Comment by mickaelistria** [comment]
Ok, I used -U and can now reproduce the issue. thanks for catching that!

**Comment by mickaelistria** [comment]
test this

**Comment by mickaelistria** [comment]
@vpakan I fixed the GenerateRepositoryFacade mojo to better support Git detached head. It has fixed the verification build.

**Pull request closed without merging**
