### PR TITLE
JBIDE-27006 - Fix several maven.itests tests (failing sporadically due to timeouts)

### PR DESCRIPTION
**Pull request by zcervink**
**JBIDE-27006 - Fix several maven.itests tests (failing sporadically due to timeouts)**

Signed-off-by: Zbynek Cervinka <zcervink@redhat.com>

**Jenkins:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/977/
**JIRA:** https://issues.redhat.com/browse/JBIDE-27006

Please review @jkopriva @odockal

### CODE REVIEW

**Comment by jkopriva** [comment]
@zcervink I see you are changing timeouts from 10s to 300s. Do you have any comparison how many tests it fixed? Thanks!

**Comment by zcervink** [comment]
> @zcervink I see you are changing timeouts from 10s to 300s. Do you have any comparison how many tests it fixed? Thanks!

That has fixed all the timeout issues in all the tests (excepts openjdk11 on win10, the win10 is slow). You can compare 2 Jenkins - before and after timeout fixes:

- **JBIDE-27006 BRANCH:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/977/
- **MASTER BRANCH:** https://dev-platform-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/maven.itests/994/

**Comment by zcervink** [comment]
@jkopriva I understand, that timeouts are not as important to fix as some other issues, but if you look at how many tests fails and needs to rerun due to them, it is really annoying.

**Comment by zcervink** [comment]
@jkopriva and one another information I should mention, I have increased the timeouts from 10s to 60s at first. Well, that has fixed only a few issues, so I have to continue and increase more (I have test all the places, where I am increasing the timeout step by step, so we can be sure the increase is not bigger than needed).

**Comment by jkopriva** [comment]
@zcervink please fix sonar, afterwards we can merge it.
And also create JIRA(if you do not have yet) for JDK 11 failures.

**Comment by zcervink** [comment]
@jkopriva All sonar issues fixed. I am not gonna run this on Jenkins again, because I have done only refactoring (I thing it is not necessary).

**Comment by zcervink** [comment]
@jkopriva The JIRA for JDK 11 failures has already been created - JBIDE-26900.

**Comment by jkopriva** [comment]
LGMT, merging.

**Pull request merged**
