### PR TITLE
JBDS-3208 use new path to upstream snapshot site >> master

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by vpakan** [comment]
test this

**Comment by vpakan** [comment]
@nickboldt verification build failed. Since we are not using JBT snapshots I think proper change reflecting renaming of property jbosstools-site-stream to jbosstools_stream is covered by #887 am I right?

**Comment by mmalina** [comment]
Yeah, I would like to know what mars/snapshots/updates is. But it seems using that would kind of defeat the use of the property since it has mars hardcoded?

**Comment by nickboldt** [comment]
It's hard coded, yes. And changes every year, as it has for the past few years.

This year as part of a many-year-long request to standardize our publishing, staging, and releasing processes for JBDS and JBT, I've been migrating content from updates/nightly/ to http://download.jboss.org/jbosstools/mars/snapshots/updates/

Similarly, builds/staging is now http://download.jboss.org/jbosstools/mars/snapshots/builds/

So, URLs embedded in parent pom and reused by downstream projects also need to change.

**Comment by nickboldt** [comment]
The reason the verification build failed is that I was waiting on multiple projects upstream of the JBT aggregates to fix their parent POM's so they could be built. You could push #887 but it's an incomplete fix; you will still need to update the full URL later anyway.

So, my advice is just wait on pushing this PR until the upstream is ready.

**Comment by vpakan** [comment]
test this

**Comment by mmalina** [comment]
OK, then I guess there is no other option for us but follow the changes. But to me the whole jbosstools_stream property is not all that useful anymore if we need to update the url manually when the time comes anyway.

**Comment by nickboldt** [comment]
The stream simply defines if you're building & publishing from master, or from the 4.3.0.*x branch.
The overall URL is still adopted from the parent pom, and we DO change it every year, because we build against a new Eclipse platform every year.

**Comment by mmalina** [comment]
The overall URL is hardcoded in our pom.xml, so we have to update it manually. It's not taken from the parent pom.

**Comment by nickboldt** [comment]
True... 

https://github.com/jbosstools/jbosstools-integration-tests/blob/master/pom.xml#L34-L35

could be changed to:

${jbosstools_site_baseurl}/jbosstools-build-sites.aggregate.site_${jbosstools_stream}/${jbosstools_site_suffix}
${jbosstools_site_baseurl}/jbosstools-build-sites.aggregate.coretests-site_${jbosstools_stream}/${jbosstools_site_suffix}

If you want to use the latest nightly build composites (1 or more builds).

Or, you could use these, to link to ONLY the latest single update site:

http://download.jboss.org/jbosstools/mars/snapshots/updates/core/${jbosstools_stream}/
http://download.jboss.org/jbosstools/mars/snapshots/updates/coretests/${jbosstools_stream}/

**Pull request closed without merging**
