### PR TITLE
Use product & make it configurable

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
This config basically behaves the same way as using <profileName> but brings a benefit of being able to update existing feature (not possible with profileName). 

`<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<configuration>
					<dependency-resolution>
						<extraRequirements>
							<requirement>
								<type>p2-installable-unit</type>
								<id>org.jboss.tools.cdi.feature.feature.group</id>
								<versionRange>0.0.0</versionRange>
							</requirement>
                                       </dependency-resolution>
                                   </configuration>
</plugin>`

This for example upgrades new cdi feature (which may have been built locally)

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rawagner** [comment]
test this

**Comment by rhopp** [comment]
Let's talk about this on our meeting.

**Comment by rawagner** [comment]
test this

**Pull request merged**
