### PR TITLE
Added Docker abstraction for OpenShift tests and updated Deploy Image tests

### PR DESCRIPTION
**Pull request by mlabuda**
- basic docker abstraction created for OpenShift tests. RedDeer docker plugin is not used because tests will be moved to OpenShift tooling repo and abstraction is more tailored for OpenShift testing.
- fixed logging tests, because output of image push has changed
- added AbstractOpenShiftWizardPageTest to test suites

### CODE REVIEW

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
test this

**Comment by mlabuda** [comment]
Waiting for new TP, plugin requires RedDeer 1.2.0-SNAPSHOT bcs of tree viewer handler changes.

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
I don't see a point n duplicating code. I would suggest cooperating with @jkopriva about docker stuff.

**Comment by mlabuda** [comment]
test this

**Pull request merged**
