### PR TITLE
Retrieve token link in connection wizard implemented.

### PR DESCRIPTION
**Pull request by rhopp**

### CODE REVIEW

**Comment by rhopp** [comment]
@mlabuda could you please review?

**Comment by rhopp** [comment]
Looking at this PR I'll extract EmulatedLinkStyledText to separate class. Probably on thursday next week.

**Comment by mlabuda** [comment]
Looks fine, just few notices:
- you could add whole binaries folder to gitignore, because archive is platform dependent and with new version of oc binary we would have to update also gitignore again. Maybe you could also add target folder to gitignore
- as you mentioned, extracting EmulatedLinkStyledText is a good idea

**Comment by rhopp** [comment]
test this

**Comment by rhopp** [comment]
Issues raised here were addressed. Also Bundle-RequiredExecutionEnvironment was increaed to JavaSE-1.8 (to support lambda expressions used in this PR. I hope this is OK. Assigning to psrna.

**Pull request merged**
